
services:
  edurobo:
    image: edurobo
    build: .
    container_name: edurobo
    ports:
      - "7862:7860"
    volumes:
      - .:/home/user/app
    restart: unless-stopped
    networks:
      - edurobo-shared-net

networks:
  edurobo-shared-net:
    external: true
